# Generated by Django 4.2.27 on 2026-06-10 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='importjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='exportjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
