# Generated by Django 4.1.1 on 2023-09-21 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Invoice Date')),
                ('balance_from_previous_term', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['student', 'term'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payable_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Basic Salary')),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('period', models.CharField(max_length=50)),
                ('Paid_Date', models.DateField(auto_now_add=True, verbose_name='Paid Date')),
            ],
            options={
                'ordering': ['staff'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(verbose_name='Amount')),
                ('date_paid', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Deductions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('period', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['staff'],
            },
        ),
        migrations.CreateModel(
            name='TaxTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chargeableIncome', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Earnings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('period', models.CharField(max_length=50)),
                ('earnings', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_account.earnings')),
            ],
            options={
                'ordering': ['staff'],
            },
        ),
    ]
