# Generated by Django 3.0.7 on 2022-10-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_core', '0001_initial'),
        ('student_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='class_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_core.Courses'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_core.SessionYearModel'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_core.Students'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_core.AcademicTerm'),
        ),
    ]
