# Generated by Django 4.1.1 on 2023-11-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_account', '0001_initial'),
        ('student_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_earnings',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.staffs'),
        ),
        migrations.AddField(
            model_name='staff_deductions',
            name='deductions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_account.deductions'),
        ),
        migrations.AddField(
            model_name='staff_deductions',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_account.payroll'),
        ),
        migrations.AddField(
            model_name='staff_deductions',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.staffs'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_account.invoice', verbose_name='Bills'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.staffs'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='feetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_account.feetype'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_account.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='class_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_core.courses'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_core.sessionyearmodel'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_core.students'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_core.academicterm'),
        ),
    ]
