# Generated by Django 4.1.1 on 2023-02-19 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0002_invoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Paid'),
        ),
    ]
