# Generated by Django 4.1.1 on 2023-11-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
