# Generated by Django 4.1.1 on 2023-11-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0003_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
