# Generated by Django 4.1.1 on 2023-11-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0004_delete_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
