# Generated by Django 4.1.1 on 2023-11-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0005_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
