# Generated by Django 4.1.1 on 2023-03-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0005_alter_receipt_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='description',
        ),
    ]
