# Generated by Django 4.1.1 on 2023-11-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0006_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
