# Generated by Django 4.1.1 on 2023-11-21 18:39

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('adminSignature', models.FileField(blank=True, null=True, upload_to='school/')),
                ('logo', models.FileField(blank=True, null=True, upload_to='school/')),
                ('seal', models.FileField(blank=True, null=True, upload_to='school/')),
                ('school_id', models.CharField(default=school.models.unique_school_id, max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
