# Generated by Django 4.1.1 on 2023-01-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='adminSignaure',
            field=models.FileField(blank=True, null=True, upload_to='school/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='school/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='seal',
            field=models.FileField(blank=True, null=True, upload_to='school/'),
        ),
    ]
