# Generated by Django 4.1.1 on 2023-11-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0003_role_staffs_role'),
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.bank'),
        ),
    ]
