# Generated by Django 4.1.1 on 2023-01-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_adminsignaure_alter_school_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='adminSignaure',
            new_name='adminSignature',
        ),
    ]
