# Generated by Django 4.1.1 on 2023-02-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sub_category',
            new_name='category',
        ),
    ]
