# Generated by Django 4.1.1 on 2023-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_rename_sub_category_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stationery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Stationery Item')),
                ('desc', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Stationery Items',
            },
        ),
    ]
