# Generated by Django 3.0.7 on 2022-12-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20221230_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'List of Sub categories'},
        ),
        migrations.AddField(
            model_name='book',
            name='bookpage',
            field=models.FileField(null=True, upload_to='bookpage/'),
        ),
        migrations.AddField(
            model_name='book',
            name='coverpage',
            field=models.FileField(null=True, upload_to='coverpage/'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='Author/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookstore.Category'),
        ),
    ]
