# Generated by Django 4.1.1 on 2023-02-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0010_alter_students_admin'),
        ('bookstore', '0003_stationery'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_core.courses')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.stationery')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_core.sessionyearmodel')),
            ],
            options={
                'verbose_name': 'stationery',
            },
        ),
    ]
