# Generated by Django 3.0.7 on 2022-12-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20221231_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='totalrating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='book',
            name='totalreview',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookpage',
            field=models.FileField(blank=True, null=True, upload_to='Bookpage/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='coverpage',
            field=models.FileField(blank=True, null=True, upload_to='Coverpage/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
