# Generated by Django 3.0.7 on 2023-01-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20221231_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Category'),
        ),
    ]
