# Generated by Django 4.1.1 on 2023-02-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_remove_requireditem_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requireditem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
