# Generated by Django 4.1.1 on 2023-03-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_alter_requireditem_qty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requireditem',
            options={'ordering': ['item'], 'verbose_name': 'stationery'},
        ),
    ]
