# Generated by Django 3.0.7 on 2022-10-15 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student_exam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_core', '0003_auto_20221011_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('passcode', models.CharField(default=student_exam.models.unique_passcode, max_length=100)),
                ('content', models.TextField()),
                ('upload', models.FileField(default='No file uploaded', null=True, upload_to='assignments/')),
                ('due_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.Courses')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.Subjects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(default=student_exam.models.unique_passcode, max_length=100)),
                ('upload', models.FileField(upload_to='submissions/')),
                ('answer', models.TextField(blank=True, default='None', null=True)),
                ('submitted_at', models.DateField(auto_now=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('grade', models.CharField(blank=True, default='No grade yet', max_length=100, null=True)),
                ('feedback', models.CharField(blank=True, default='No feedback yet', max_length=255, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='student_exam.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
