# Generated by Django 3.0.7 on 2022-10-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='upload',
            field=models.FileField(default='No file uploaded', upload_to='assignments/'),
        ),
    ]
