# Generated by Django 4.1.1 on 2023-01-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_exam', '0002_auto_20221017_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lb', models.IntegerField()),
                ('grade', models.CharField(max_length=15)),
                ('remark', models.CharField(max_length=50)),
            ],
        ),
    ]
