# Generated by Django 4.1.1 on 2023-03-04 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0011_alter_customuser_managers'),
        ('student_exam', '0002_alter_assignment_id_alter_exercise_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.courses', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='upload',
            field=models.FileField(default='', upload_to='assignments/'),
        ),
    ]
