# Generated by Django 4.1.1 on 2023-01-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_exam', '0003_gradebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradebook',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
