# Generated by Django 4.1.1 on 2023-01-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_exam', '0004_gradebook_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallGradebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lb', models.IntegerField()),
                ('grade', models.CharField(max_length=15)),
                ('remark', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
