# Generated by Django 4.1.1 on 2023-01-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_exam', '0005_overallgradebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
