# Generated by Django 3.0.7 on 2022-10-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['attendance_date'], 'verbose_name': 'Attendance'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['subject_name'], 'verbose_name': 'Subject'},
        ),
    ]
