# Generated by Django 3.0.7 on 2022-10-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0002_auto_20221008_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name']},
        ),
    ]
