# Generated by Django 4.1.1 on 2023-11-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0003_role_staffs_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.role'),
        ),
    ]
