# Generated by Django 3.0.7 on 2022-12-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0004_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.Gender'),
        ),
    ]
