# Generated by Django 4.1.1 on 2023-02-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0004_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['id'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_core.students'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionyearmodel',
            name='re_opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='staff/'),
        ),
        migrations.AddField(
            model_name='students',
            name='delete_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.gender'),
        ),
        migrations.CreateModel(
            name='ConductInterestRemarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conduct', models.CharField(blank=True, max_length=255, null=True)),
                ('interest', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.students')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cls_id', models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.courses')),
                ('staff_id', models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.staffs')),
            ],
        ),
    ]
