# Generated by Django 4.1.1 on 2023-02-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0005_alter_courses_options_remove_attendance_subject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='students/'),
        ),
    ]
