# Generated by Django 3.0.7 on 2022-12-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0006_auto_20221217_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='delete_flag',
            field=models.IntegerField(default=0),
        ),
    ]
