# Generated by Django 4.1.1 on 2023-02-20 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0006_alter_students_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='students',
            name='parent_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='parent_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='parent_first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='parent_last_name',
            field=models.CharField(default='lastname', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='parent_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'Completed')], default=1, max_length=2),
        ),
    ]
