# Generated by Django 4.1.1 on 2023-02-21 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0007_students_dob_students_parent_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='parent_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Contact Number format! Must be between 10 and 15 digits', regex='^[0-9]{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='parent_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Invalid email format')]),
        ),
    ]
