# Generated by Django 3.0.7 on 2022-12-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0007_students_delete_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2),
        ),
    ]
