# Generated by Django 4.1.1 on 2023-01-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0008_students_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
