# Generated by Django 4.1.1 on 2023-01-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0009_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionyearmodel',
            name='re_opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
