# Generated by Django 4.1.1 on 2023-01-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0010_sessionyearmodel_re_opening_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='staff_id',
        ),
    ]
