# Generated by Django 4.1.1 on 2023-01-22 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0011_remove_subjects_course_id_remove_subjects_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cls_id', models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.courses')),
                ('staff_id', models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.staffs')),
            ],
        ),
    ]
