# Generated by Django 4.1.1 on 2023-01-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0012_classteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='staff/'),
        ),
    ]
