# Generated by Django 4.1.1 on 2023-01-25 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0013_staffs_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductInterestRemarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conduct', models.TextField(blank=True, null=True)),
                ('interest', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_core.students')),
            ],
        ),
    ]
