# Generated by Django 4.1.1 on 2023-01-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0014_conductinterestremarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductinterestremarks',
            name='conduct',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conductinterestremarks',
            name='interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conductinterestremarks',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
