# Generated by Django 4.1.1 on 2023-02-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0015_alter_conductinterestremarks_conduct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['id'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
