# Generated by Django 4.1.1 on 2023-02-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='division',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
