name: CI/CD Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PA_SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder_will_be_ignored'
          if_key_exists: replace

      - name: Execute Background SSH Commands
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.PA_USERNAME }}@ssh.pythonanywhere.com "bash -c 'echo \"=== START DEPLOY ===\" && cd ~/student_management_system && echo \"-> Pulling Git Code\" && git pull origin main && echo \"-> Activating Env\" && source ~/.virtualenvs/myenv/bin/activate && echo \"-> Running Migrations\" && python manage.py migrate && echo \"-> Collecting Static Files\" && python manage.py collectstatic --noinput && echo \"-> Reloading WSGI Server\" && touch /var/www/${{ secrets.PA_USERNAME }}_pythonanywhere_com_wsgi.py && echo \"=== DEPLOY SUCCESSFUL ===\"'"
