name: CI/CD Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PA_SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder_will_be_ignored'
          if_key_exists: replace

      - name: Run Remote Deployment Script
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.PA_USERNAME }}@ssh.pythonanywhere.com "~/auto_deploy.sh"
